# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27-django-18
  - TOX_ENV=py27-django-19
  - TOX_ENV=py27-django-110
  - TOX_ENV=lint

matrix:
  fast_finish: true

services:
  - redis-server

install: pip install -r requirements_test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
